/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SorteioRouteImport } from './routes/sorteio'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated.accounts'
import { Route as AuthenticatedCashbackRouteImport } from './routes/_authenticated.cashback'
import { Route as AuthenticatedCatalogRouteImport } from './routes/_authenticated.catalog'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated.clients'
import { Route as AuthenticatedCreditRouteImport } from './routes/_authenticated.credit'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedLabelsRouteImport } from './routes/_authenticated.labels'
import { Route as AuthenticatedMaterialsRouteImport } from './routes/_authenticated.materials'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated.production'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated.products'
import { Route as AuthenticatedPromotionsRouteImport } from './routes/_authenticated.promotions'
import { Route as AuthenticatedPurchaseBoardRouteImport } from './routes/_authenticated.purchase-board'
import { Route as AuthenticatedPurchasesRouteImport } from './routes/_authenticated.purchases'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated.reports'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated.sales'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated.stock'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated.transactions'
import { Route as ApiPublicSorteioInfoRouteImport } from './routes/api/public/sorteio-info'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SorteioRoute = SorteioRouteImport.update({
  id: '/sorteio',
  path: '/sorteio',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCashbackRoute = AuthenticatedCashbackRouteImport.update({
  id: '/cashback',
  path: '/cashback',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCatalogRoute = AuthenticatedCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCreditRoute = AuthenticatedCreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLabelsRoute = AuthenticatedLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMaterialsRoute = AuthenticatedMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPromotionsRoute = AuthenticatedPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPurchaseBoardRoute =
  AuthenticatedPurchaseBoardRouteImport.update({
    id: '/purchase-board',
    path: '/purchase-board',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchasesRoute = AuthenticatedPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicSorteioInfoRoute = ApiPublicSorteioInfoRouteImport.update({
  id: '/api/public/sorteio-info',
  path: '/api/public/sorteio-info',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sorteio': typeof SorteioRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/cashback': typeof AuthenticatedCashbackRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/credit': typeof AuthenticatedCreditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/labels': typeof AuthenticatedLabelsRoute
  '/materials': typeof AuthenticatedMaterialsRoute
  '/production': typeof AuthenticatedProductionRoute
  '/products': typeof AuthenticatedProductsRoute
  '/promotions': typeof AuthenticatedPromotionsRoute
  '/purchase-board': typeof AuthenticatedPurchaseBoardRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/api/public/sorteio-info': typeof ApiPublicSorteioInfoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sorteio': typeof SorteioRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/cashback': typeof AuthenticatedCashbackRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/credit': typeof AuthenticatedCreditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/labels': typeof AuthenticatedLabelsRoute
  '/materials': typeof AuthenticatedMaterialsRoute
  '/production': typeof AuthenticatedProductionRoute
  '/products': typeof AuthenticatedProductsRoute
  '/promotions': typeof AuthenticatedPromotionsRoute
  '/purchase-board': typeof AuthenticatedPurchaseBoardRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/api/public/sorteio-info': typeof ApiPublicSorteioInfoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/sorteio': typeof SorteioRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/cashback': typeof AuthenticatedCashbackRoute
  '/_authenticated/catalog': typeof AuthenticatedCatalogRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/credit': typeof AuthenticatedCreditRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/labels': typeof AuthenticatedLabelsRoute
  '/_authenticated/materials': typeof AuthenticatedMaterialsRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/promotions': typeof AuthenticatedPromotionsRoute
  '/_authenticated/purchase-board': typeof AuthenticatedPurchaseBoardRoute
  '/_authenticated/purchases': typeof AuthenticatedPurchasesRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/api/public/sorteio-info': typeof ApiPublicSorteioInfoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sorteio'
    | '/accounts'
    | '/cashback'
    | '/catalog'
    | '/clients'
    | '/credit'
    | '/dashboard'
    | '/labels'
    | '/materials'
    | '/production'
    | '/products'
    | '/promotions'
    | '/purchase-board'
    | '/purchases'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/stock'
    | '/transactions'
    | '/api/public/sorteio-info'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sorteio'
    | '/accounts'
    | '/cashback'
    | '/catalog'
    | '/clients'
    | '/credit'
    | '/dashboard'
    | '/labels'
    | '/materials'
    | '/production'
    | '/products'
    | '/promotions'
    | '/purchase-board'
    | '/purchases'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/stock'
    | '/transactions'
    | '/api/public/sorteio-info'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sorteio'
    | '/_authenticated/accounts'
    | '/_authenticated/cashback'
    | '/_authenticated/catalog'
    | '/_authenticated/clients'
    | '/_authenticated/credit'
    | '/_authenticated/dashboard'
    | '/_authenticated/labels'
    | '/_authenticated/materials'
    | '/_authenticated/production'
    | '/_authenticated/products'
    | '/_authenticated/promotions'
    | '/_authenticated/purchase-board'
    | '/_authenticated/purchases'
    | '/_authenticated/reports'
    | '/_authenticated/sales'
    | '/_authenticated/settings'
    | '/_authenticated/stock'
    | '/_authenticated/transactions'
    | '/api/public/sorteio-info'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  SorteioRoute: typeof SorteioRoute
  ApiPublicSorteioInfoRoute: typeof ApiPublicSorteioInfoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorteio': {
      id: '/sorteio'
      path: '/sorteio'
      fullPath: '/sorteio'
      preLoaderRoute: typeof SorteioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cashback': {
      id: '/_authenticated/cashback'
      path: '/cashback'
      fullPath: '/cashback'
      preLoaderRoute: typeof AuthenticatedCashbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/credit': {
      id: '/_authenticated/credit'
      path: '/credit'
      fullPath: '/credit'
      preLoaderRoute: typeof AuthenticatedCreditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/labels': {
      id: '/_authenticated/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof AuthenticatedLabelsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/materials': {
      id: '/_authenticated/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof AuthenticatedMaterialsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/promotions': {
      id: '/_authenticated/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof AuthenticatedPromotionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchase-board': {
      id: '/_authenticated/purchase-board'
      path: '/purchase-board'
      fullPath: '/purchase-board'
      preLoaderRoute: typeof AuthenticatedPurchaseBoardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchases': {
      id: '/_authenticated/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AuthenticatedPurchasesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/sorteio-info': {
      id: '/api/public/sorteio-info'
      path: '/api/public/sorteio-info'
      fullPath: '/api/public/sorteio-info'
      preLoaderRoute: typeof ApiPublicSorteioInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedCashbackRoute: typeof AuthenticatedCashbackRoute
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedCreditRoute: typeof AuthenticatedCreditRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLabelsRoute: typeof AuthenticatedLabelsRoute
  AuthenticatedMaterialsRoute: typeof AuthenticatedMaterialsRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedPromotionsRoute: typeof AuthenticatedPromotionsRoute
  AuthenticatedPurchaseBoardRoute: typeof AuthenticatedPurchaseBoardRoute
  AuthenticatedPurchasesRoute: typeof AuthenticatedPurchasesRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedCashbackRoute: AuthenticatedCashbackRoute,
  AuthenticatedCatalogRoute: AuthenticatedCatalogRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedCreditRoute: AuthenticatedCreditRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLabelsRoute: AuthenticatedLabelsRoute,
  AuthenticatedMaterialsRoute: AuthenticatedMaterialsRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedPromotionsRoute: AuthenticatedPromotionsRoute,
  AuthenticatedPurchaseBoardRoute: AuthenticatedPurchaseBoardRoute,
  AuthenticatedPurchasesRoute: AuthenticatedPurchasesRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  SorteioRoute: SorteioRoute,
  ApiPublicSorteioInfoRoute: ApiPublicSorteioInfoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
