CREATE INDEX IF NOT EXISTS idx_sales_created_at ON public.sales (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sales_client_id ON public.sales (client_id);
CREATE INDEX IF NOT EXISTS idx_sales_status ON public.sales (status);
CREATE INDEX IF NOT EXISTS idx_sale_items_sale_id ON public.sale_items (sale_id);
CREATE INDEX IF NOT EXISTS idx_sale_items_product_id ON public.sale_items (product_id);
CREATE INDEX IF NOT EXISTS idx_sale_payments_sale_id ON public.sale_payments (sale_id);
CREATE INDEX IF NOT EXISTS idx_sale_installments_sale_id ON public.sale_installments (sale_id);
CREATE INDEX IF NOT EXISTS idx_sale_installments_due_date ON public.sale_installments (due_date);
CREATE INDEX IF NOT EXISTS idx_debt_payments_sale_id ON public.debt_payments (sale_id);
CREATE INDEX IF NOT EXISTS idx_transactions_created_at ON public.transactions (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_transactions_sale_id ON public.transactions (sale_id);
CREATE INDEX IF NOT EXISTS idx_transactions_account_id ON public.transactions (account_id);
CREATE INDEX IF NOT EXISTS idx_transactions_purchase_id ON public.transactions (purchase_id);
CREATE INDEX IF NOT EXISTS idx_transactions_client_id ON public.transactions (client_id);
CREATE INDEX IF NOT EXISTS idx_cashback_entries_client_id ON public.cashback_entries (client_id);
CREATE INDEX IF NOT EXISTS idx_cashback_entries_sale_id ON public.cashback_entries (sale_id);
CREATE INDEX IF NOT EXISTS idx_purchase_items_purchase_id ON public.purchase_items (purchase_id);
CREATE INDEX IF NOT EXISTS idx_purchase_items_material_id ON public.purchase_items (material_id);
CREATE INDEX IF NOT EXISTS idx_purchases_created_at ON public.purchases (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_purchases_supplier_id ON public.purchases (supplier_id);
CREATE INDEX IF NOT EXISTS idx_product_materials_product_id ON public.product_materials (product_id);
CREATE INDEX IF NOT EXISTS idx_product_materials_material_id ON public.product_materials (material_id);
CREATE INDEX IF NOT EXISTS idx_material_variations_material_id ON public.material_variations (material_id);
CREATE INDEX IF NOT EXISTS idx_material_cuts_material_id ON public.material_cuts (material_id);
CREATE INDEX IF NOT EXISTS idx_production_orders_product_id ON public.production_orders (product_id);
CREATE INDEX IF NOT EXISTS idx_production_orders_status ON public.production_orders (status);
CREATE INDEX IF NOT EXISTS idx_stock_products_produto_id ON public.stock_products (produto_id);
CREATE INDEX IF NOT EXISTS idx_stock_products_ordem_id ON public.stock_products (ordem_producao_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_created_at ON public.audit_log (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON public.notifications (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_qr_promo_history_sale_id ON public.qr_promo_history (sale_id);
CREATE INDEX IF NOT EXISTS idx_qr_promo_history_client_id ON public.qr_promo_history (client_id);
CREATE INDEX IF NOT EXISTS idx_products_active ON public.products (active);
CREATE INDEX IF NOT EXISTS idx_clients_name ON public.clients (name);
ANALYZE;