DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'sale_items' AND COLUMN_NAME = 'numeracao') THEN
        ALTER TABLE public.sale_items ADD COLUMN numeracao TEXT;
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'sales_items') THEN
        IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'sales_items' AND COLUMN_NAME = 'numeracao') THEN
            ALTER TABLE public.sales_items ADD COLUMN numeracao TEXT;
        END IF;
    END IF;
END $$;
